# Generated by Django 5.0.4 on 2024-04-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('python', 'Python Projects'), ('web', 'Web Development Projects')], max_length=50)),
                ('subcategory', models.CharField(choices=[('backend', 'Back End'), ('frontend', 'Front End'), ('full', 'Full-stack'), ('arcade', 'Arcade'), ('gui', 'GUI'), ('python_script', 'Python Scripting'), ('datascience', 'Data Science'), ('other', 'Other'), ('web', 'Python Web')], max_length=50)),
                ('example_link', models.URLField()),
                ('github_link', models.URLField()),
                ('picture', models.URLField(default='https://www.w3schools.com/django/django_add_image.php')),
            ],
        ),
    ]
