# Generated by Django 5.0.4 on 2024-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.TextField(),
        ),
    ]
